name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/ci.yml"
      - "go.mod"
      - "go.sum"
      - "**/*.go"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "go.mod"
      - "go.sum"
      - "**/*.go"

jobs:
  lint:
    name: Lint
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2

  build:
    name: Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.x

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: make
